<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Purchase Order — Low Stock</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1a1a1a; background: #fff; }

        /* ── Header ── */
        .header { background: #1a1a2e; color: #fff; padding: 24px 30px 20px; }
        .header-top { display: flex; justify-content: space-between; align-items: flex-start; }
        .brand { font-size: 22px; font-weight: 700; letter-spacing: 1px; color: #f59e0b; }
        .brand-sub { font-size: 10px; color: #a0aec0; margin-top: 2px; }
        .doc-title { text-align: right; }
        .doc-title h2 { font-size: 16px; font-weight: 700; color: #f59e0b; }
        .doc-title p  { font-size: 9px; color: #a0aec0; margin-top: 2px; }
        .header-meta { margin-top: 14px; border-top: 1px solid rgba(255,255,255,0.15); padding-top: 12px; display: flex; gap: 40px; }
        .meta-item { }
        .meta-label { font-size: 8px; text-transform: uppercase; letter-spacing: 1px; color: #a0aec0; }
        .meta-value { font-size: 11px; color: #fff; margin-top: 2px; font-weight: 600; }

        /* ── Alert banner ── */
        .alert-banner { background: #fffbeb; border-left: 4px solid #f59e0b; padding: 10px 30px; font-size: 10px; color: #92400e; }

        /* ── Section ── */
        .section { padding: 20px 30px; }
        .section-title { font-size: 13px; font-weight: 700; color: #1a1a2e; margin-bottom: 12px; border-bottom: 2px solid #f59e0b; padding-bottom: 4px; }

        /* ── Table ── */
        table { width: 100%; border-collapse: collapse; font-size: 10px; }
        thead tr { background: #1a1a2e; color: #fff; }
        thead th { padding: 9px 10px; text-align: left; font-size: 9px; text-transform: uppercase; letter-spacing: 0.5px; }
        thead th.right { text-align: right; }
        tbody tr:nth-child(even) { background: #f8fafc; }
        tbody tr { border-bottom: 1px solid #e2e8f0; }
        tbody td { padding: 8px 10px; vertical-align: middle; }
        tbody td.right { text-align: right; }
        .badge-low { background: #fef3c7; color: #92400e; border-radius: 3px; padding: 2px 6px; font-size: 8px; font-weight: 700; }
        .deficit { color: #dc2626; font-weight: 700; }

        /* ── Summary box ── */
        .summary { margin: 0 30px 20px; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 14px 18px; }
        .summary-grid { display: flex; gap: 30px; }
        .summary-item { }
        .summary-label { font-size: 8px; text-transform: uppercase; letter-spacing: 1px; color: #64748b; }
        .summary-value { font-size: 18px; font-weight: 700; color: #1a1a2e; }
        .summary-value.amber { color: #f59e0b; }
        .summary-value.red { color: #dc2626; }

        /* ── Footer ── */
        .footer { margin: 10px 30px 0; border-top: 1px solid #e2e8f0; padding-top: 10px; font-size: 8px; color: #94a3b8; display: flex; justify-content: space-between; }
        .footer-note { font-style: italic; }
    </style>
</head>
<body>

    <!-- Header -->
    <div class="header">
        <div class="header-top">
            <div>
                <div class="brand">AutoFuel</div>
                <div class="brand-sub">Inventory Management System</div>
            </div>
            <div class="doc-title">
                <h2>PURCHASE ORDER</h2>
                <p>Low-Stock Items</p>
            </div>
        </div>
        <div class="header-meta">
            <div class="meta-item">
                <div class="meta-label">Generated On</div>
                <div class="meta-value">{{ now()->format('d/m/Y H:i') }}</div>
            </div>
            <div class="meta-item">
                <div class="meta-label">Total Items</div>
                <div class="meta-value">{{ $items->count() }}</div>
            </div>
            <div class="meta-item">
                <div class="meta-label">Generated by</div>
                <div class="meta-value">{{ $user }}</div>
            </div>
        </div>
    </div>

    <!-- Alert -->
    <div class="alert-banner">
        ⚠️ The following items have reached or fallen below their minimum stock level and require restocking.
    </div>

    <!-- Summary -->
    <div class="section">
        <div class="section-title">Resumen</div>
        <div class="summary">
            <div class="summary-grid">
                <div class="summary-item">
                    <div class="summary-label">Items en Stock Bajo</div>
                    <div class="summary-value amber">{{ $items->count() }}</div>
                </div>
                <div class="summary-item">
                    <div class="summary-label">Estimated Restocking Cost</div>
                    <div class="summary-value">
                        ${{ number_format($items->sum(function($i){ return max(0, $i->min_stock - $i->current_stock + 1) * ($i->cost_per_unit ?? 0); }), 2) }}
                    </div>
                </div>
                <div class="summary-item">
                    <div class="summary-label">Items Without a Defined Cost</div>
                    <div class="summary-value red">{{ $items->whereNull('cost_per_unit')->count() }}</div>
                </div>
            </div>
        </div>
    </div>

    <!-- Items Table -->
    <div class="section" style="padding-top:0">
        <div class="section-title">Item Details</div>
        <table>
            <thead>
                <tr>
                    <th style="width:5%">#</th>
                    <th style="width:28%">Item</th>
                    <th style="width:14%">Category</th>
                    <th style="width:8%">Unidad</th>
                    <th class="right" style="width:10%">Stock Actual</th>
                    <th class="right" style="width:10%">Minimum</th>
                    <th class="right" style="width:10%">Shortage</th>
                    <th class="right" style="width:10%">Costo/U</th>
                    <th class="right" style="width:13%">Costo Estimado</th>
                </tr>
            </thead>
            <tbody>
                @foreach($items as $index => $item)
                @php
                    $deficit   = max(0, $item->min_stock - $item->current_stock + 1);
                    $unitCost  = $item->cost_per_unit ?? 0;
                    $estimated = $deficit * $unitCost;
                @endphp
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td><strong>{{ $item->name }}</strong></td>
                    <td>{{ $item->category?->name ?? '—' }}</td>
                    <td>{{ $item->unit }}</td>
                    <td class="right"><span class="badge-low">{{ number_format($item->current_stock, 2) }}</span></td>
                    <td class="right">{{ number_format($item->min_stock, 2) }}</td>
                    <td class="right deficit">{{ number_format($deficit, 2) }}</td>
                    <td class="right">{{ $item->cost_per_unit ? '$'.number_format($item->cost_per_unit, 2) : '—' }}</td>
                    <td class="right">{{ $item->cost_per_unit ? '$'.number_format($estimated, 2) : '—' }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <!-- Footer -->
    <div class="footer">
        <div class="footer-note">Document generated automatically by the AutoFuel inventory system.</div>
        <div>Page 1</div>
    </div>

</body>
</html>
